import type { AppProps } from "next/app";
import { CacheProvider, EmotionCache } from "@emotion/react";
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "styles/theme";
import createEmotionCache from "util/creationEmotionCache";
import Head from "next/head";
import MainBlock from "@/component/MainBlock";
import FontGroup from "@/component/FontGroup";

const clientSideEmotionCache = createEmotionCache();

interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache;
}

export default function App({ Component, emotionCache = clientSideEmotionCache, pageProps }: MyAppProps) {
  return (
    <CacheProvider value={emotionCache}>
      <Head>
        <title>Congratulation 🥳</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FontGroup />
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <MainBlock>
          <Component {...pageProps} />
        </MainBlock>
      </ThemeProvider>
    </CacheProvider>
  );
}
