import type { AppProps } from "next/app";
import { CacheProvider, EmotionCache } from "@emotion/react";
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "styles/theme";
import createEmotionCache from "util/creationEmotionCache";
import Head from "next/head";
import MainBlock from "@/component/Common/MainBlock";
import FontGroup from "@/component/Common/FontGroup";
import router from "next/router";
import { SWRConfig } from "swr";
import axios from "axios";

const clientSideEmotionCache = createEmotionCache();

interface MyAppProps extends AppProps {
  emotionCache?: EmotionCache;
}

export default function App({ Component, emotionCache = clientSideEmotionCache, pageProps }: MyAppProps) {
  return (
    <CacheProvider value={emotionCache}>
      <SWRConfig
        value={{
          fetcher: (url) => axios.get(url).then((res) => res.data),
          onError: (error) => {
            if (error.response.status === 404) {
              router.replace("/");
            }
          },
        }}
      >
        <Head>
          <title>Congratulation 🥳</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <FontGroup />
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <MainBlock>
            <Component {...pageProps} />
          </MainBlock>
        </ThemeProvider>
      </SWRConfig>
    </CacheProvider>
  );
}
