import Head from "next/head";
import Link from "next/link";
import NewButton from "@/component/NewButton";

export default function Home() {
  return (
    <>
      <Head>
        <title>생일 축하해요!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>This is Home Page</main>
      <Link href="/create">
        <NewButton text="케이크 생성" />
      </Link>
    </>
  );
}
